services:
  tunnel:
    build:
      context: .
      dockerfile: Dockerfile.tunnel
    restart: unless-stopped
    # Use extra_hosts to map host.docker.internal to host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Define cloudflared environment variables
      - NO_AUTOUPDATE=true
    # Isolated network
    networks:
      - monacofaculty-tunnel-network

networks:
  monacofaculty-tunnel-network:
    driver: bridge
