services:
  tunnel:
    build:
      context: .
      dockerfile: Dockerfile.tunnel
    restart: unless-stopped
    network_mode: host
    environment:
      # Define cloudflared environment variables
      - NO_AUTOUPDATE=true
